# CI - Cypress Tests
on:
	push:
		branches:
			- master

jobs:
	cypress-tests:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout repository
				uses: actions/checkout@v3

			- name: Setup Node.js
				uses: actions/setup-node@v3
				with:
					node-version: '20'

			- name: Install Cypress
				run: npm install cypress --save-dev

			- name: Install dependencies
				run: npm install

			- name: Run Cypress in background
				run: |
					npx cypress run &
					sleep 10

			- name: Run tests
				run: echo "Testes executados após Cypress rodar em background."
